repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
    -   id: ruff
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: >-
            python -c 'import sys, os; 
            entry = ".venv/Scripts/pytest" if sys.platform == "win32" 
            else ".venv/bin/pytest"; 
            os.system(entry + " " + " ".join(sys.argv[1:]))'
        language: system
        types: [python]
        pass_filenames: false